apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nodejs-app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-nodejs-app
  template:
    metadata:
      labels:
        app: simple-nodejs-app
    spec:
      containers:
      - name: simple-nodejs-app
        image: grygamar/simple-nodejs-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: simple-nodejs-app
  namespace: app
spec:
  selector:
    app: simple-nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
