---
- name: Setup K3s cluster
  hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: Include K3s token
      include_vars: k3s_token.yml
      tags: always
  tasks:
    - name: Update and upgrade packages
      apt:
        update_cache: yes
        upgrade: safe

    - name: Install dependencies
      apt:
        name:
          - curl
          - unzip

    - name: Install k3sup
      become: yes
      get_url:
        url: https://github.com/alexellis/k3sup/releases/download/0.11.0/k3sup-armhf
        dest: /usr/local/bin/k3sup
        mode: '0755'

    - name: Generate K3s token on the first control plane node
      command: k3sup token create
      register: k3s_token_output
      when: inventory_hostname == '192.168.0.238'

    - name: Set K3s token fact for other nodes
      set_fact:
        k3s_token: "{{ hostvars['192.168.0.238']['k3s_token_output']['stdout'] }}"
      when: inventory_hostname != '192.168.0.238'

    - name: Install K3s on the first control plane node
      command: "curl -sfL https://get.k3s.io | K3S_TOKEN='{{ k3s_token }}' sh -s - server --tls-san '{{ ansible_host }}'"
      when: inventory_hostname == '192.168.0.238'

    - name: Install K3s on the remaining control plane nodes using the K3s token
      ansible.builtin.shell:
        cmd: "curl -sfL https://get.k3s.io | K3S_TOKEN={{ k3s_token }} sh -s - server --tls-san {{ ansible_ssh_host }} --server https://192.168.0.238:6443"
      when: "'192.168.0.238' not in inventory_hostname"
      tags:
        - k3s_install

