---
- name: K3s HA quick-start
  hosts: all
  become: yes
  tasks:
    - name: Download and install K3s on the first control plane node
      ansible.builtin.shell: >-
        curl -sfL https://get.k3s.io | sh -s - --disable servicelb --disable traefik
      args:
        warn: no
      when: inventory_hostname == '192.168.1.2'
      register: k3s_install

    - name: Save the K3s token from the first control plane node
      become: no
      delegate_to: 192.168.1.2
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "./k3s.yaml"
        flat: yes
      when: inventory_hostname == '192.168.1.2'

    - name: Replace the server URL in the K3s config file
      ansible.builtin.replace:
        path: "./k3s.yaml"
        regexp: 'server: https://127.0.0.1:6443'
        replace: 'server: https://192.168.1.2:6443'
      when: inventory_hostname == '192.168.1.2'

    - name: Install K3s on the remaining control plane nodes using the K3s token
      ansible.builtin.shell: >-
        curl -sfL https://get.k3s.io | K3S_URL=https://192.168.1.2:6443 K3S_TOKEN='{{ k3s_token.stdout }}' sh -s - --disable servicelb --disable traefik --server https://192.168.1.2:6443
      args:
        warn: no
      when: inventory_hostname != '192.168.1.2'
      vars:
        k3s_token: "{{ hostvars['192.168.1.2']['k3s_install']['stdout_lines'] | select('search', 'K3S_TOKEN') | first }}"
