apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: ">= 19.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    grafana:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
      adminPassword: "test"
      service:
        type: NodePort
        port: 80
        targetPort: 3000
        nodePort: 32000
    prometheus:
      prometheusSpec:
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        service:
          type: NodePort
          port: 9090
          nodePort: 32001
    alertmanager:
      config:
        global:
          resolve_timeout: 5m
      alertmanagerSpec:
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
        service:
          type: NodePort
          port: 9093
          nodePort: 32002
