apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: prometheus-community/kube-prometheus-stack
      version: ">= 19.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    grafana:
      adminPassword: "test"
      service:
        type: NodePort
        port: 80
        targetPort: 3000
        nodePort: 32000
    prometheus:
      prometheusSpec:
        service:
          type: NodePort
          port: 9090
          nodePort: 32001
    alertmanager:
      config:
        global:
          resolve_timeout: 5m
      alertmanagerSpec:
        service:
          type: NodePort
          port: 9093
          nodePort: 32002
